/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.load("G:\\projects\\android\\_lab\\guomi\\src\\main\\jniLibs\\libgnustl_shared.so");
        System.out.println("quit");
    }
}
